//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public decimal UserId { get; set; }
        public string UserPassword { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public decimal UserPhoneNumber { get; set; }
        public string UserEmail { get; set; }
    }
}
